import "./globals.scss";
import type { Metadata } from "next";
import clsx from "clsx";
import { FontClass } from "@/utils";
import Providers from "./providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    "bg-base-50 m-auto grid min-h-screen max-w-screen-xl grid-cols-[auto_1fr] grid-rows-[auto_1fr_auto] px-8 text-foreground",
                    FontClass.DEFAULT,
                )}
            >
                <Providers>
                    <header className="col-start-1 col-end-3 bg-gray-300">
                        Header
                    </header>
                    <aside className="col-start-1 col-end-2 bg-gray-200">
                        Sidebar
                    </aside>
                    <main className="col-start-2 col-end-3 bg-gray-100 ">
                        {children}
                    </main>
                    <footer className="col-start-1 col-end-3 bg-gray-300">
                        Footer
                    </footer>
                </Providers>
            </body>
        </html>
    );
}
